workflows:
  android_debug:
    name: Android Debug
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Flutter version
        script: flutter --version
      - name: Ensure project files
        script: |
          if [ ! -d android ]; then
            flutter create .
          fi
      - name: Get packages
        script: flutter pub get
      - name: Build APK (debug)
        script: flutter build apk --debug
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
