name: build-android
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Get packages
        run: flutter pub get

      # إذا مجلد android مو موجود، نسويه من الصفر
      - name: Create Android platform if missing
        run: |
          if [ ! -d "android" ]; then
            flutter create . --org com.waslni.alami --project-name wasalni_alami --platforms=android
          fi

      # نضمن أرقام الـ SDK حتى لا يطيح Gradle على geolocator_android
      - name: Patch Android SDK versions
        run: |
          FILE=android/app/build.gradle
          echo "----- build.gradle before ----"
          cat $FILE || true
          echo "------------------------------"

          # إذا السطر مال android { ... } موجود، نضيف داخله القيم إذا ماكو
          if grep -q "android {" $FILE; then
            sed -i '/android {/a \    compileSdkVersion 34' $FILE
            sed -i 's/minSdkVersion [0-9][0-9]*/minSdkVersion 21/' $FILE
            sed -i 's/targetSdkVersion [0-9][0-9]*/targetSdkVersion 34/' $FILE
          fi

          echo "----- build.gradle after ----"
          cat $FILE || true
          echo "-----------------------------"

      - name: Build debug APK
        run: flutter build apk --debug --no-tree-shake-icons

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: build/app/outputs/flutter-apk/app-debug.apk
