name: build-android
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
            distribution: temurin
            java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
            channel: stable

      - name: Flutter pub get
        run: flutter pub get

      - name: Ensure android/ exists
        run: |
            if [ ! -d "android" ]; then
              flutter create . --platforms=android --org com.wasalni.alami --project-name wasalni_alami
            fi

      - name: Force SDK versions
        run: |
            FILE=android/app/build.gradle
            echo "----- BEFORE -----"
            cat "$FILE" || true
            echo "------------------"

            # حاول عدّل اذا السطور موجودة
            sed -i 's/compileSdkVersion \+[0-9][0-9]*/compileSdkVersion 34/' "$FILE" || true
            sed -i 's/targetSdkVersion \+[0-9][0-9]*/targetSdkVersion 34/' "$FILE" || true
            sed -i 's/minSdkVersion \+[0-9][0-9]*/minSdkVersion 21/' "$FILE" || true

            echo "----- AFTER ------"
            cat "$FILE" || true
            echo "------------------"

      - name: Build debug APK
        run: flutter build apk --debug --no-tree-shake-icons

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
            name: app-debug.apk
            path: build/app/outputs/flutter-apk/app-debug.apk
